name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.3.0)'
        required: true
        type: string

env:
  NODE_VERSION: '20'

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            platform: win
          - os: macos-latest
            platform: mac
          - os: ubuntu-latest
            platform: linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install system dependencies (Linux)
        if: matrix.platform == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libxtst6 libxrandr2 libasound2-dev libgtk-3-dev libxss1 libgconf-2-4 libxtst6 libxrandr2 libasound2-dev libpangocairo-1.0-0 libatk1.0-0 libcairo-gobject2 libgtk-3-0 libgdk-pixbuf2.0-0

      - name: Install system dependencies (macOS)
        if: matrix.platform == 'mac'
        run: |
          echo "macOS dependencies ready"

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Rebuild native modules
        run: |
          npm rebuild robotjs --build-from-source || echo "RobotJS build failed, continuing without it"
        continue-on-error: true

      - name: Run type checking
        run: npm run typecheck

      - name: Build application
        run: npm run build

      - name: Install app dependencies (Electron)
        run: npm run postinstall

      - name: Build Electron app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false
          ROBOTJS_SKIP_OPTIONAL: true
        run: |
          if [[ "${{ matrix.platform }}" == "win" ]]; then
            echo "Building for Windows..."
            npm run package:win || (echo "Windows build failed, trying alternative..." && npm run dist)
          elif [[ "${{ matrix.platform }}" == "mac" ]]; then
            echo "Building for macOS..."
            npm run package:mac || (echo "macOS build failed, trying alternative..." && npm run dist)
          elif [[ "${{ matrix.platform }}" == "linux" ]]; then
            echo "Building for Linux..."
            npm run package:linux || (echo "Linux build failed, trying alternative..." && npm run dist)
          fi
        shell: bash

      - name: List build outputs
        run: |
          echo "Contents of dist-electron (if exists):"
          ls -la dist-electron/ 2>/dev/null || echo "No dist-electron directory found"
          echo "Contents of dist (if exists):"
          ls -la dist/ 2>/dev/null || echo "No dist directory found"
          echo "Looking for any build artifacts:"
          find . -name "*.exe" -o -name "*.dmg" -o -name "*.AppImage" -o -name "*.deb" 2>/dev/null || echo "No build artifacts found"
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: release-${{ matrix.platform }}
          path: |
            dist-electron/*.exe
            dist-electron/*.dmg
            dist-electron/*.AppImage
            dist-electron/*.deb
            dist/*.exe
            dist/*.dmg
            dist/*.AppImage
            dist/*.deb
            release/*.exe
            release/*.dmg
            release/*.AppImage
            release/*.deb
          retention-days: 5
          if-no-files-found: warn

  create-release:
    needs: build-and-release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Get version from tag
        id: version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=${TAG_NAME#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: New World Chat AI ${{ steps.version.outputs.version }}
          files: |
            ./artifacts/**/*.exe
            ./artifacts/**/*.dmg
            ./artifacts/**/*.AppImage
            ./artifacts/**/*.deb
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
