name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string

env:
  NODE_VERSION: '20'  # Use LTS for best compatibility

permissions:
  contents: write
  packages: write
  actions: read

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Build Windows executable
        run: npx electron-builder build --win --publish=never

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: |
            dist-electron/*.exe
            dist-electron/*.exe.blockmap

      - name: Generate release notes with Gemini AI
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          choco install jq -y
          COMMITS=$(git log -10 --pretty=format:"%s" | jq -R -s -c '.')
          PROMPT="Write concise, user-friendly release notes for these commits: $COMMITS"
          RESPONSE=$(curl -s -X POST "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=$GEMINI_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"contents\":[{\"parts\":[{\"text\":\"$PROMPT\"}]}]}" )
          echo "$RESPONSE" | jq -r '.candidates[0].content.parts[0].text' > RELEASE_NOTES.md

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: New World Chat AI ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            dist-electron/*.exe
            dist-electron/*.exe.blockmap
          body_path: RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}