name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string

env:
  NODE_VERSION: '20'  # Use LTS for best compatibility

permissions:
  contents: write
  packages: write
  actions: read

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Build Windows executable
        run: npx electron-builder build --win --publish=never

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: |
            dist-electron/*.exe
            dist-electron/*.exe.blockmap

      - name: Set release version
        id: set-version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "RELEASE_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            TAG=${{ github.ref_name }}
            echo "RELEASE_VERSION=${TAG#v}" >> $GITHUB_ENV
          fi

      - name: Generate release notes with Gemini AI
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          choco install jq -y
          COMMITS=$(git log -10 --pretty=format:"%s" | jq -R -s -c '.')
          # Escape double quotes and newlines for safe JSON
          ESCAPED_COMMITS=$(echo "$COMMITS" | sed ':a;N;$!ba;s/\"/\\\"/g;s/\\n/ /g')
          PROMPT="Write concise, user-friendly release notes for version $RELEASE_VERSION. Commits: $ESCAPED_COMMITS"
          RESPONSE=$(curl -s -X POST "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=$GEMINI_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"contents\":[{\"parts\":[{\"text\":\"$PROMPT\"}]}]}" )
          echo "Gemini raw response:" >&2
          echo "$RESPONSE" >&2
          NOTES=$(echo "$RESPONSE" | jq -r '.candidates[0].content.parts[0].text')
          if [ -z "$NOTES" ] || [ "$NOTES" = "null" ]; then
            echo "[Gemini API did not return release notes. Using fallback.]" >&2
            NOTES="Release notes could not be generated automatically. Please review commits manually."
          fi
          echo "$NOTES" > RELEASE_NOTES.md

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: New World Chat AI v${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
          files: |
            dist-electron/*.exe
            dist-electron/*.exe.blockmap
          body_path: RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}